NORTH = 'north'
EAST = 'east'
SOUTH = 'south'
WEST = 'west'
DIRECTIONS = [NORTH, EAST, SOUTH, WEST]
SCREEN_WIDTH = 80
TAVERN = 'tavern'
TOWN_SQUARE = 'town square'
BLACK_FOREST = 'black forest'
GENERAL_STORE = 'general store'
STARTING_ROOM = TOWN_SQUARE
RED = 'red'